# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node Github CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js node-version [12.x]
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install and test
      run: |
        npm install
        npm test
      env:
        CI: true
  build:
    needs: test

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@master
        - name: Publish to Docker Repo
          uses: elgohr/Publish-Docker-Github-Action@master
          with:
            name: yokarak/billelind
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets. DOCKER_PASSWORD }}