# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node CI

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      working-directory: ./server

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js node-version [14.x]
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: npm ci (more strict than install)
    - run: npm ci 
      working-directory: ${{env.working-directory}}
    - run: npm run build --if-present
      working-directory: ${{env.working-directory}}
    - run: npm test
      working-directory: ${{env.working-directory}}